-- CREATE TABLE "Dziesma" (
-- 	"ID"	INTEGER NOT NULL,
-- 	"nosaukums"	TEXT,
-- 	"izp_id"	INTEGER,
-- 	"zanrs_id"	INTEGER,
-- 	PRIMARY KEY("ID"),
-- 	FOREIGN KEY("izp_id") REFERENCES "Izpilditajs"("izp_ID"),
-- 	FOREIGN KEY("zanrs_id") REFERENCES "Zanrs"("zanrs_ID")
-- );
-- CREATE TABLE "Izpilditajs" (
-- 	"izp_ID"	INTEGER NOT NULL,
-- 	"izp"	TEXT,
-- 	PRIMARY KEY("izp_ID")
-- );
-- CREATE TABLE "Zanrs" (
-- 	"zanrs_ID"	INTEGER NOT NULL,
-- 	"zanrs"	INTEGER,
-- 	PRIMARY KEY("zanrs_ID")
-- );
-- INSERT INTO Izpilditajs (izp) VALUES 
-- ('Dons'),
-- ('Prāta vētra'),
-- ('Bermudu Divstūris');
-- INSERT INTO Zanrs (zanrs) VALUES 
-- ('Pop'),
-- ('Rock'),
-- ('Party');
-- 
-- INSERT INTO Dziesma(nosaukums,izp_id, zanrs_id) VALUES 
-- ('Lauzto šķēpu karaļvalsts', 1, 1),
-- ('Pēdējā vēstule', 1, 1),
-- ('Lidmašīnas', 2, 2),
-- ('Mana dziesma', 2, 2),
-- ('Sarkanās', 3, 3);
-- UPDATE Dziesma
-- SET nosaukums = "Pēdējā vēstule (Remix)"
-- where nosaukums = "Pēdējā vēstule"
-- SELECT nosaukums, Izpilditajs.izp from Dziesma
-- INNER JOIN Izpilditajs
-- on Izpilditajs.izp_ID = Dziesma.izp_id
-- neatļaus izdzēst prāta vetras ierakstu, jo prata vetras ieraksta id nem berna tabula dziesmas.