-- BRĪDINĀJUMS: Šis skripts "sabojās" tavus datus praktiskajam darbam!
-- 
-- 1. Ieviešam "Baložu armiju" (Spams Laukumā C)
-- INSERT INTO Dzivnieks (suga, vards, vecums, bar_laiks, kopejs_ID, lauk_ID) VALUES 
-- ('balodis', 'Pēcis', 2, 'visu laiku', 4, 3),
-- ('balodis', 'Jēcis', 1, 'visu laiku', 4, 3),
-- ('balodis', 'Kēcis', 3, 'visu laiku', 4, 3),
-- ('balodis', 'Mēcis', 2, 'visu laiku', 4, 3),
-- ('balodis', 'Tēcis', 1, 'visu laiku', 4, 3),
-- ('balodis', 'Sēcis', 4, 'visu laiku', 4, 3),
-- ('balodis', 'Lēcis', 2, 'visu laiku', 4, 3),
-- ('balodis', 'Zēcis', 1, 'visu laiku', 4, 3);
-- 
-- 2. Ievadām kļūdainus datus (Loģikas kļūdas)
-- Bruņurupucis ar negatīvu vecumu un nepareizu kopēju
-- INSERT INTO Dzivnieks (suga, vards, vecums, bar_laiks, kopejs_ID, lauk_ID)
-- VALUES ('bruņurupucis', 'Zibsnis', "-100", '08:00', 4, 1);
-- 
-- 3. Dublējošs darbinieks (Cilvēciskā kļūda)
-- Mums jau ir "Džefs" (visticamāk ID=1), bet kāds ievadīja vēlreiz neprecīzi
-- INSERT INTO Kopejs (vards) 
-- VALUES ('Dzefs '); -- Pievērs uzmanību garumzīmei
-- 
-- Piesaistām jauno "Džefu" (kuram būs jauns ID) pie jauna dzīvnieka
-- INSERT INTO Dzivnieks (suga, vards, vecums, bar_laiks, kopejs_ID, lauk_ID)
-- VALUES ('pērtiķis', 'Čita', "5", '09:00', (SELECT MAX(kopejs_ID) FROM kopejs), 1);
-- 
-- 4. Formatēšanas kļūdas (Mazie burti)
-- INSERT INTO Dzivnieks (suga, vards, vecums, bar_laiks, kopejs_ID, lauk_ID) 
-- VALUES("zebra", "svītrainīte", "4 gadi", "11:00", 3, 1);
-- DELETE FROM Dzivnieks
-- WHERE suga = "balodis";
-- UPDATE Dzivnieks 
-- SET vecums = 100
-- WHERE vecums = "-100"
-- UPDATE Dzivnieks
-- set vards = "Svītrainīte"
-- where vards = "svītrainīte"
-- UPDATE Dzivnieks
-- SET kopejs_ID = 1
-- where kopejs_ID = 5;
DELETE from Kopejs
where kopejs_ID > 5
-- DELETE from Dzivnieks 
-- WHERE ID > 40